name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATA_IN_DIR: data
      DATA_OUT_DIR: output

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Lint
        run: flake8 src tests --max-line-length=100 --ignore=E203,W503

      - name: Run tests
        run: |
          pytest -q
