name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATA_IN_DIR: data
      DATA_OUT_DIR: output

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'   # opcional: alinea con tu local; usa '3.11' si prefieres
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          else
            # deps mínimas para tests/lint
            pip install pytest flake8 pandas pyarrow
          fi

      - name: Lint
        run: flake8 src tests --max-line-length=100 --ignore=E203,W503

      - name: Run tests
        run: python -m pytest -q
